#!/usr/bin/env python3
"""Regenerate the `test-vectors/sources/` section of `manifest.toml` listing
all files with their sizes and SHA-256s. The other sections are preserved.

Usage: python3 tools/gen-manifest.py
"""
import hashlib
from pathlib import Path
import sys


REPO = Path(__file__).resolve().parent.parent
SOURCES = REPO / "test-vectors" / "sources"
MANIFEST = REPO / "test-vectors" / "manifest.toml"


def sha256_of(path: Path) -> str:
    h = hashlib.sha256()
    with path.open("rb") as f:
        for chunk in iter(lambda: f.read(65536), b""):
            h.update(chunk)
    return h.hexdigest()


def main() -> int:
    if not SOURCES.is_dir():
        print(f"missing {SOURCES}", file=sys.stderr)
        return 1

    lines = []
    lines.append("# ISO 21496-1 metadata fixture matrix — regenerated by")
    lines.append("# tools/gen-iso21496.py + tools/gen-manifest.py. 22 cases × 2")
    lines.append("# wire variants (JpegApp2 + AvifTmap) = 44 files. Each pair covers")
    lines.append("# one axis of the spec: direction, channels, common-denom, varied")
    lines.append("# denominators, value extremes, gamma, writer_version, etc.")
    lines.append("")
    for path in sorted(SOURCES.glob("*.bin")):
        rel = path.relative_to(REPO / "test-vectors").as_posix()
        sha = sha256_of(path)
        size = path.stat().st_size
        lines.append("[[iso21496]]")
        lines.append(f'file = "{rel}"')
        lines.append(f"size = {size}")
        lines.append(f'sha256 = "{sha}"')
        lines.append('generated_by = "tools/gen-iso21496.py"')
        lines.append("")

    out = "\n".join(lines)
    # Rewrite just the [[iso21496]] section in the existing manifest by stripping
    # the old one and appending the new one.
    if MANIFEST.exists():
        txt = MANIFEST.read_text()
        start = txt.find("# ISO 21496-1 metadata blobs — for parser-level tests")
        if start == -1:
            # Try the new marker
            start = txt.find("# ISO 21496-1 metadata fixture matrix")
        if start != -1:
            # Find the next non-iso21496 section OR end of file
            remainder = txt[start:]
            # Skip all [[iso21496]] blocks and their separators
            idx = 0
            blocks = remainder.split("\n\n")
            kept = []
            for b in blocks:
                if b.lstrip().startswith("[[iso21496]]") or b.lstrip().startswith("# ISO 21496-1"):
                    continue
                kept.append(b)
            new_tail = "\n\n".join(kept)
            MANIFEST.write_text(txt[:start] + out + ("\n\n" + new_tail if new_tail.strip() else "\n"))
        else:
            MANIFEST.write_text(txt.rstrip() + "\n\n" + out + "\n")
    else:
        MANIFEST.write_text(out + "\n")

    print(f"wrote {len(list(SOURCES.glob('*.bin')))} entries to {MANIFEST}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
